// resources.js
export const resources = {
  api: [
    { name: "垃圾桶的 SAI 的 api 转译服务（已失效）", description: "垃圾桶的 SAI 的 api 转译服务，支持 SAI 的流式输出、推理模型...", link: "https://flowus.cn/share/ae562c6b-4341-4abe-b72e-0346e24d2fb2?code=PYQS3X【FlowUs 息流】垃圾桶的 SAI 的 api 转译服务" },
    { name: "UomgAPI", description: "稳定、快速、免费的 API 接口服务", link: "https://api.uomg.com/" },
    { name: "Qeeo API", description: "WelCome！━(｀∀´)ノ亻!欢迎使用Qeeo API！", link: "https://qeeodocs.feishu.cn/wiki/J1MAwlkeBiPQsokAmZDcXE9nn4c" },
    { name: "AmethystAI", description: "免费的ai接口，需加群后注册使用", link: "https://nav.amethyst.ltd/" },
    { name: "算了么API", description: "OpenAI 接口聚合管理，支持多种渠道", link: "https://api.suanli.cn/pricing" },
    { name: "【已失效】垃圾桶的 Markdown 转 Html 的Api", description: "适用于 CoCo 编辑器", link: "https://flowus.cn/share/e36680eb-a23d-40bf-b5f8-2ad08cb170da?code=PYQS3X" },
    { name: "ColudAI(秋田人工智能)开发文档", description: "免费调用自家的Ai 的 Api", link: "https://www.yuque.com/liushiancoludai/oei1as" },
    { name: "（已失效）在线图片颜色提取api", description: "有时会卡死，不推荐使用！（来自@垃圾桶）", link: "https://flowus.cn/share/5d9a11ee-f1c8-4210-8266-42e2b7342376?code=PYQS3X" },
    { name: "openrouter", description: "一个 Ai 接口调用平台（有调用次数限制）", link: "https://openrouter.ai/" },
    { name: "多coco-cocoAPI", description: "多coco-cocoAPI为您提供超好用的API，让您在文档中掌握API的用法", link: "https://cocoapi.codejun.top/" },
    { name: "星之阁API", description: "免费API大全", link: "https://api.xingzhige.com/" },
    { name: "画的博客", description: "虽说是博客，但也是有API文档的", link: "https://s.jixiejidiguan.top/" },
    { name: "夏柔API", description: "夏柔 - 分享的API永不收费", link: "https://api.aa1.cn/" },
    { name: "小小API", description: "小小API是一个稳定 快速 的 API 接口服务", link: "https://xxapi.cn/" },
    { name: "PearAPI", description: "永久免费API", link: "https://api.pearktrue.cn/dashboard/home" },
    { name: "咔咔云API", description: "易用的接口平台", link: "https://api.kkjsz.cn/" },
    { name: "龙珠API", description: "龙珠API，是一个免费在线API测试服务，稳定可靠的站点!", link: "https://www.hhlqilongzhu.cn/" },
    { name: "独角兽API", description: "独角兽API是一款好用、有趣、简便的API接口", link: "https://d.ovooa.cc/" },
    { name: "笒鬼鬼API", description: "笒鬼鬼自用API数据接口调用服务平台", link: "https://api.cenguigui.cn/" },
    { name: "云智API", description: "云智API【接口列表】", link: "https://api.jkyai.top/" },
    { name: "起零API", description: "面向企业与个人提供免费、全面且高质量的API数据接口资源", link: "https://api.istero.com/" },
    { name: "简心API", description: "为用户提供安全可靠的接口服务平台", link: "https://api.qvqa.cn/" },
    { name: "陌染-API", description: "致力于为用户提供稳定、快速的免费API数据接口服务", link: "https://apii.xhcmz.cn/" },
    { name: "彬红茶API", description: "致力于为用户提供优质api调用服务", link: "https://api.redcha.cn/" },
    { name: "稳定API", description: "稳定快速的API调用平台", link: "https://api.xingchenfu.xyz/" },
    { name: "星宇云API", description: "星宇云API,\"提供简单,快速上手的API接口服务\"", link: "api" },
    { name: "Free-Qwen3", description: "世界首个免费无限制 分布式 AI 算力平台", link: "https://qwen3.slmnb.cn/" },
    { name: "VV开放API", description: "提供了一些开放API", link: "https://iftc-api.apifox.cn" },
    { name: "云智API", description: "为开发者打造的优质接口服务平台", link: "https://yunzhiapi.cn/" }
  ],
  component: [
    { name: "Qeeo 控件库", description: "WelCome！━(*｀∀´*)ノ亻!欢迎使用Qeeo控件库！", link: "https://qeeodocs.feishu.cn/wiki/WtsSwo92IiN44okEY47c4KHwnPe" },
    { name: "Hor 控件库", description: "功能新颖别致，十分好用～(๑¯∀¯๑) ", link: "https://www.yuque.com/seekyhor/horkj" },
    { name: "柠檬桶控件库", description: "Hi~ o(￣▽￣)ブ欢迎使用柠檬桶控件库！", link: "https://flowus.cn/share/96f5c6cd-577f-46ec-a014-572571bc6770?code=PYQS3X" },
    { name: "Artkit控件补全计划（已失效）", description: "Artkit控件补全计划，致力于为小白创作者提供一个便捷、高效的解决方案。", link: "https://www.yuque.com/apanzinc/artkit" },
    { name: "zxcoco", description: "zxcoco知识库资源", link: "https://zx-create.feishu.cn/wiki/DKKxw1DSpiL2g0kAcB8cXCmAnEb" },
    { name: "ReducedRadius的控件库", description: "ReducedRadius的控件中心", link: "https://reducedradius.netlify.app/widget/" },
    { name: "XJの控件库", description: "50余控件，历史悠久，底蕴丰厚，带给你最佳的控件体验", link: "https://xjwangdage.feishu.cn/wiki/KQECwTAJqiVpXjk3ZtFcqEDVnyc?from=from_copylink" },
    { name: "小宏XeLaの控件文档", description: "这里有一些小型控件，欢迎使用~", link: "https://btmu8uap4l.feishu.cn/wiki/wikcnnjCV7uB9FxC1CcSevmvAWb" },
    { name: "青柠系控件", description: "简洁至上、稳定性强、持续更新", link: "https://doc.lihouse.xyz/" },
    { name: "SLIGHTNING 的控件", description: "SLIGHTNING 的控件", link: "https://s-lightning.github.io/projects/#project--codemao--coco--widget--widgets" },
    { name: "SLIGHTNING CoCo 控件框架", description: "工程化 CoCo 自定义控件开发解决方案", link: "https://s-lightning.github.io/slightning-coco-widget/" }
  ],
  data: [
    { name: "AUTHIOR", description: "适用于coco编辑器的一体化登录/注册验证/数据控件，保证优雅，易用与稳定性", link: "https://open.lihouse.xyz/#/" },
    { name: "数据COOL", description: "下一代coco/cp编辑器的云数据库程序", link: "https://open.lihouse.xyz/dc#/" },
    { name: "点鸭MySQL数据表", description: "点鸭平台MySQL数据表", link: "https://dbs.pgaot.com/steer" },
    { name: "【停止注册】CoDrive", description: "【停止注册】CoDrive数据存储服务（已注册账号的仍然可以正常使用）", link: "https://drive.amethyst.ltd" },
    { name: "COCO控件分享平台", description: "COCO控件分享平台", link: "https://jmm666.nocode.host/#/co" },
    { name: "CoCo应用商店", description: "应用已收录70+", link: "https://www.lihouse.xyz/cocoapps/#/" },
    { name: "XJの作品库", description: "收录了作者的开源作品", link: "https://xjwangdage.feishu.cn/wiki/wikcnsoahQouMo8Qh3GK8iO6UOQ?from=from_copylink" },
    { name: "【可能搬迁了】Amethyst Free Intelligence", description: "【可能搬迁了】一个免费、强大、无限制的 Gemini AI 接口中转", link: "https://free.amethyst.ltd/#home" },
    { name: "星梦临时网盘", description: "星梦出品，必属精品", link: "https://pan.cloudroo.top/home?path=%2F" },
    { name: "（已停运）点扣社区", description: "是的，这是一个社区（2025.10.5 停运）", link: "https://work.hopex.top/pickcoco" },
    { name: "PICKDUCK数据表控制台-极艺星社", description: "PICKDUCK数据表的控制台", link: "https://dbs.pgaot.com/steer" },
    { name: "MoreLine资源站", description: "这是一个资源共享，社区适合个人开发者发布软件，适合查找与分享实用资源工具", link: "https://more.jsoftstudio.top/" },
    { name: "文件快递柜", description: "这是一款使用flask开发的文件快递柜\n本站建立初衷是为了方便文件暂时存放与转移、陌生人快捷传递文件\n代码已在GitHub开源，欢迎部署", link: "https://file.jsoftstudio.top/" },
    { name: "J账号登录接口", description: "登录与管理J账号，使用J账号登录/注册您的项目", link: "https://github.com/kamcdev/Jsoft_Jid_moreapi" },
    { name: "同学盘", description: "同学创新提供的免费网盘，暂定50GB免费，用尽后可免费添加", link: "https://pan.txcxgzs.com" },
    { name: "IFTC官网", description: "IFTC官网", link: "https://iftc.koyeb.app" }
  ],
  editor: [
    { name: "CoCo 编辑器", description: "进入强大的在线代码编辑器", link: "https://coco.codemao.cn/home" },
    { name: "CoCopro", description: "进入CoCopro在线编辑器", link: "https://ccp.cloudroo.top/editor/" },
    { name: "Waddle", description: "让世界上没有难做的CoCo控件", link: "https://waddle.cocotais.cn/" },
    { name: "CoCo Next 镜像", description: "基于 CoCo 源代码计划 二次开发的 CoCo，旨在通过直接修改编辑器代码的方式修复 CoCo 的缺陷、增强 CoCo 的功能。", link: "https://next.ccwidget.top/editor/" }
  ],
  kongjianshangcheng: [
    { name: "CCWidget（原“没有名”）", description: "自定义控件工具、文档，商城", link: "https://ccwidget.top/" },
    { name: "耶椰椰", description: "耶椰椰，耶椰椰，我们都爱耶椰椰！（控件分享与下载平台）", link: "https://open.lihouse.xyz/ye#/archieve" },
    { name: "PICKDUCK-点鸭社区-控件商城", description: "开箱即用的JavaScript控件商城", link: "https://shequ.pgaot.com/?mod=cocojs" },
    { name: "CoCo-Community", description: "第三方社区", link: "https://cc.zitzhen.cn" }
  ],
  maotool: [
    { name: "棕榈酸鸭AI控件", description: "通过 ai 快速编写控件", link: "https://www.tbox.cn/share/202508APAvTl00517109?platform=WebService" },
    { name: "【已失效】FlowChunkFlex", description: "基于Vue3+Vite6；流式读取文件，分块并发提交至【编程猫七牛云对象存储】以解决大小限制；支持中断自动重传，默认单块最大15MB，并发上传数2。", link: "https://file.cjack.cfd/" },
    { name: "Omnia APK 处理服务", description: "对CoCo打包的APK进行处理（改包）", link: "https://open.lihouse.xyz/elixir" },
    { name: "【已失效】点鸭-编程猫CDN对象存储", description: "文件转链接神器，但文件大小限制 30MB", link: "https://shequ.pgaot.com/?mod=codemaocdn" },
    { name: "WidgetRemover", description: "WidgetRemover是一款可以快速删除 CoCo 编辑器中不需要的自定义控件的工具。", link: "https://codemao.yuque.com/kzbwh0/coco_guide/vym98wznz81dr1gv" },
    { name: "CoCoKit 控件开发包", description: "由 @琦琦 制作的控件扩展包，让你可以使用简洁易懂的代码快速开发出强大的控件。", link: "https://www.yuque.com/yuqueyonghuslrsu6/qcqduw/uya7g9piiu5mcy28" },
    { name: "Cohooker", description: "通过 Cordova API 来让应用实现更复杂的功能", link: "https://yiv49471wlw.feishu.cn/wiki/RWQxwFOsbiuzMCkjFXCcMp8Qn1f" },
    { name: "数据COOL", description: "青柠系的，不好用就怪了", link: "https://open.lihouse.xyz/dc#/" },
    { name: "在线作品伪装", description: "之前绕审核用的在线作品伪装", link: "https://www.lihouse.xyz/bypass/" },
    { name: "作品分享审核绕过脚本", description: "用于绕过 CoCo 作品分享审核的用户脚本，可以让你的作品能发布到社区和 H5。这是一个用户脚本，需要使用用户脚本管理器（如窜改猴、油猴）加载；Greasy Fork 需要加速器才能打开；CoCo 交流群群文件里搜索“作品分享审核绕过”也可以找到该脚本", link: "https://greasyfork.org/zh-CN/scripts/487985" },
    { name: "文件分享系统", description: "上传您的文件并获取分享链接", link: "https://wenjianshangchuan.nocode.host/#/" }
  ],
  mengzhongshui: [
    { name: "生日快乐-垃圾桶", description: "🎂致敬原作者", link: "https://db0l8fnn8oqtof.database.nocode.cn/storage/v1/object/public/wenjian/anonymous/1776442057920_vo7gqnae80s.jpg" },
    { name: "垃圾桶", description: "本网站的原作者（这个网站是盗版，点击查看盗版许可）", link: "https://neko-page.github.io/src/coco/img/permission.png" },
    { name: "风哲", description: "神经病、脑残、脑瘫、癔想症、自大得要💩、招笑低能孩、九年义务教育都没上过😂（QQ:2786015868）", link: "https://static.codemao.cn/pickduck/Hk5dtZA2ee.png?hash=FrHNdFMuCcYJxY8ZzoHV-Csrfch8" },
    { name: "青界官网", description: "暂无描述", link: "https://www.qscx1.cn/" },
    { name: "梦中水大嘿客", description: "梦中水大嘿客这招太狠了😭😭😭", link: "https://shequ.codemao.cn/user/15980757" },
    { name: "小未-《努力奔跑》", description: "跑 不停努力的奔跑...", link: "https://www.bilibili.com/video/BV1zp4y1c7eq/" },
    { name: "小未-《Run and Run(努力奔跑 - 英文版)》", description: "Run and Run...", link: "https://www.bilibili.com/video/BV1cXuHeGEG5/" },
    { name: "小猫", description: "(这是我)臭垃圾桶我恨你！", link: "https://static.codemao.cn/pickduck/HyIQDQmdle.png?hash=FpoaZzw8idNDN2k8koxti2PWQHl_" },
    { name: "Tomo（小阅）（小小小小羊～)", description: "投票入榜的，该项跳转到的是投票最终统计截图", link: "https://db0l8fnn8oqtof.database.nocode.cn/storage/v1/object/public/wenjian/anonymous/1771171548018_cu3n5w5ayt.png" }
  ],
  teshu: [
    { name: "编程猫纪念碑", description: "此地空余黄鹤楼...", link: "https://shequ.codemao.cn/community/1620865" },
    { name: "点猫 | BCM-PICK", description: "现在 ，我与你相遇", link: "https://www.yuque.com/zaona/pick" },
    { name: "CoCo 快捷导航-投票广场", description: "欢迎各位参加投票～", link: "https://coco.nocode.host/#/vote-square" }
  ],
  tool: [
    { name: "图像转换器", description: "免费在线转换图像", link: "https://www.freeconvert.com/zh/image-converter" },
    { name: "WebP 转PNG", description: "免费在线将 WebP 转换为 PNG", link: "https://www.freeconvert.com/zh/webp-to-png" },
    { name: "JFIF到PNG转换器", description: "免费在线将 JFIF 转换为 PNG", link: "https://www.freeconvert.com/zh/jfif-to-png" },
    { name: "PNG转SVG", description: "从 PNG 图像创建漂亮的 SVG（可缩放矢量图形）", link: "https://www.freeconvert.com/zh/png-to-svg" },
    { name: "HEIC转JPG", description: "将 HEIC 转换为最高质量的 JPG 的最佳网络应用程序", link: "https://www.freeconvert.com/zh/heic-to-jpg" },
    { name: "HEIC到PNG转换器", description: "免费在线将 HEIC 转换为 PNG", link: "https://www.freeconvert.com/zh/heic-to-png" },
    { name: "WebP 转JPG", description: "在线免费快速将 WebP 格式转换为 JPG（JPEG）", link: "https://www.freeconvert.com/zh/webp-to-jpg" },
    { name: "SVG转换器", description: "从任何图像创建完美的 SVG（可缩放矢量图形）", link: "https://www.freeconvert.com/zh/svg-converter" },
    { name: "PDF转换器", description: "免费在线转换为 PDF 格式", link: "https://www.freeconvert.com/zh/pdf-converter" },
    { name: "文档转换器", description: "在线转换文档文件", link: "https://www.freeconvert.com/zh/document-converter" },
    { name: "电子书转换器", description: "将您的电子书和文档转换为 epub、mobi、azw3 等", link: "https://www.freeconvert.com/zh/ebook-converter" },
    { name: "PDF到WORD转换器", description: "免费在线将 PDF 转换为 WORD", link: "https://www.freeconvert.com/zh/pdf-to-word" },
    { name: "PDF转JPG", description: "在线免费将 PDF 转换为 JPG 的最佳方法", link: "https://www.freeconvert.com/zh/pdf-to-jpg" },
    { name: "PDF到EPUB转换器", description: "免费在线将 PDF 转换为 EPUB", link: "https://www.freeconvert.com/zh/pdf-to-epub" },
    { name: "EPUB到PDF转换器", description: "免费在线将 EPUB 转换为 PDF", link: "https://www.freeconvert.com/zh/epub-to-pdf" },
    { name: "HEIC到PDF转换器", description: "免费在线将 HEIC 转换为 PDF", link: "https://www.freeconvert.com/zh/heic-to-pdf" },
    { name: "DOCX到PDF转换器", description: "免费在线将 DOCX 转换为 PDF", link: "https://www.freeconvert.com/zh/docx-to-pdf" },
    { name: "JPG转PDF", description: "最佳免费在线将 JPG 转换为 PDF 的工具", link: "https://www.freeconvert.com/zh/jpg-to-pdf" },
    { name: "视频转 GIF 转换器", description: "最佳免费在线将视频转换为 GIF 动画的工具", link: "https://www.freeconvert.com/zh/convert/video-to-gif" },
    { name: "MP4 到 GIF 转换器", description: "在线免费将 MP4 转换为 GIF 动画的最佳工具", link: "https://www.freeconvert.com/zh/convert/mp4-to-gif" },
    { name: "WebM 转 GIF", description: "轻松在线将 WebM 文件转换为 GIF 动画", link: "https://www.freeconvert.com/zh/convert/webm-to-gif" },
    { name: "APNG 到 GIF 转换器", description: "将 APNG（动画 PNG）转换为 GIF 格式的最快方法", link: "https://www.freeconvert.com/zh/apng-to-gif" },
    { name: "GIF 到 MP4", description: "免费在线将 GIF 转换为 MP4", link: "https://www.freeconvert.com/zh/convert/gif-to-mp4" },
    { name: "GIF到APNG转换器", description: "免费在线将 GIF 转换为 APNG", link: "https://www.freeconvert.com/zh/gif-to-apng" },
    { name: "图像转 GIF", description: "用图像制作 GIF", link: "https://www.freeconvert.com/zh/image-to-gif" },
    { name: "单位换算器", description: "多单位换算器", link: "https://www.freeconvert.com/zh/unit-converter" },
    { name: "CST到EST转换器", description: "在 Central Standard Time（CST）和 Eastern Standard Time（EST）之间转换", link: "https://www.freeconvert.com/zh/time/cst-to-est" },
    { name: "在线档案转换器", description: "轻松将您的档案转换为 RAR、ZIP、Tar、Gz、7z 等", link: "https://www.freeconvert.com/zh/archive-converter" },
    { name: "视频压缩器", description: "世界上最好的视频压缩工具，可减少视频文件大小", link: "https://www.freeconvert.com/zh/video-compressor" },
    { name: "MP3压缩器", description: "轻松压缩 MP3 文件的最佳网络应用程序", link: "https://www.freeconvert.com/zh/mp3-compressor" },
    { name: "WAV 压缩器", description: "最佳网络应用程序，可轻松压缩 WAV 音频文件", link: "https://www.freeconvert.com/zh/wav-compressor" },
    { name: "图像压缩器", description: "最佳图像压缩工具，可在压缩图像文件的同时保持图像质量", link: "https://www.freeconvert.com/zh/image-compressor" },
    { name: "压缩 JPEG", description: "轻松压缩 JPEG 图像的最佳网络应用程序", link: "https://www.freeconvert.com/zh/compress-jpeg" },
    { name: "压缩 PNG", description: "在线压缩 PNG 图像并保持图像质量的最佳工具", link: "https://www.freeconvert.com/zh/compress-png" },
    { name: "压缩 PDF", description: "免费在线减小 PDF 文件大小", link: "https://www.freeconvert.com/zh/compress-pdf" },
    { name: "GIF压缩器", description: "世界上最好的 GIF 压缩工具，可减少 GIF 文件大小", link: "https://www.freeconvert.com/zh/gif-compressor" },
    { name: "视频裁剪器", description: "在线快速免费裁剪视频文件", link: "https://www.freeconvert.com/zh/crop-video" },
    { name: "视频修剪器", description: "在线修剪视频文件以删除不需要的部分", link: "https://www.freeconvert.com/zh/video-trimmer" },
    { name: "GIF 制作器", description: "轻松将图片制作成 GIF", link: "https://www.freeconvert.com/zh/gif-maker" },
    { name: "图像调整器", description: "免费在线轻松调整图像大小", link: "https://imageresizer.com/" },
    { name: "裁剪图像", description: "免费在线快速裁剪图像文件！", link: "https://imageresizer.com/crop-image" },
    { name: "颜色选择器", description: "一个颜色选择器", link: "https://imageresizer.com/color-picker" },
    { name: "旋转图像", description: "旋转图像工具", link: "https://imageresizer.com/rotate-image" },
    { name: "翻转图像", description: "翻转图像工具", link: "https://imageresizer.com/flip-image" },
    { name: "图片放大", description: "快速图像放大工具，可使照片变大", link: "https://imageresizer.com/image-enlarger" },
    { name: "合并 PDF", description: "使用我们易于使用的在线 PDF 合并工具，轻松将 PDF 合并为单个文档", link: "https://www.freeconvert.com/zh/merge-pdf" },
    { name: "拆分PDF", description: "轻松将 PDF 文件拆分为单独的页面或自定义页面范围", link: "https://www.freeconvert.com/zh/split-pdf" },
    { name: "在线拼合 PDF", description: "只需单击一下，即可将交互元素、表单域和图层转换为不可编辑的 PDF", link: "https://www.freeconvert.com/zh/flatten-pdf" },
    { name: "调整 PDF 大小", description: "简单易用的 PDF 调整工具，快速调整页面尺寸并优化分辨率", link: "https://www.freeconvert.com/zh/resize-pdf" },
    { name: "解锁PDF", description: "强大的 PDF 密码删除工具,轻松解锁 PDF 文件并删除密码", link: "https://www.freeconvert.com/zh/unlock-pdf" },
    { name: "旋转 PDF", description: "轻松在线快速旋转 PDF 页面", link: "https://www.freeconvert.com/zh/rotate-pdf" },
    { name: "密码保护 PDF", description: "易于使用的在线工具添加密码，保护您的文档安全", link: "https://www.freeconvert.com/zh/password-protect-pdf" },
    { name: "从 PDF 中提取图像", description: "免费在线工具立即从任何 PDF 文件中提取高质量图像", link: "https://www.freeconvert.com/zh/extract-images-from-pdf" },
    { name: "PDF页面删除器", description: "轻松从您的 PDF 文件中删除页面", link: "https://www.freeconvert.com/zh/pdf-page-remover" },
    { name: "从 PDF 中提取页面", description: "选择要保留的页面，立即下载新的、精简的 PDF 文件", link: "https://www.freeconvert.com/zh/extract-pages-from-pdf" },
    { name: "宣传图设计制作", description: "可以方便地设计、制作作品的宣传图", link: "https://shots.so/" },
    { name: "性压抑指数计算器", description: "基于科学研究的心理测评工具", link: "https://xyy.gta4.bio/" },
    { name: "TRAE", description: "Trae 旗下的 AI IDE 产品，以智能生产力为核心，无缝融入你的开发流程", link: "https://www.trae.cn/" },
    { name: "文件下载加速", description: "支持对GitHub等国外任何文件的高速下载,拒绝等待!", link: "https://down.npee.cn/" },
    { name: "在线 Markdown 编辑器", description: "好用，就是访问有点慢", link: "https://xdxsb.top/FreeEditor/" },
    { name: "Crx 搜搜", description: "浏览器拓展和应用下载站", link: "https://www.crxsoso.com/?utm=gotab.cn" },
    { name: "在线免费文字转语音【马克配音】", description: "有字数上限，部分场景下还需要登录", link: "https://ttsmaker.cn/" },
    { name: "在线配音 - 记灵配音", description: "好用，就是音色有点少", link: "https://peiyin.remeins.com/index/tools?from=index" },
    { name: "移除背景 - 制作图片透明背景", description: "在线免费去除背景。只需上传任何图片，数秒后即可获得带透明背景的图像。", link: "https://removebg.net/zh/remove-background" },
    { name: "临时邮箱 - 一次性临时电子邮件服务", description: "Temp Mail 提安全、匿名、一次性的临时电子邮件地址。", link: "https://mail.cx/zh/" },
    { name: "临时邮箱 - 十秒钟内收到邮件", description: "TempMail临时邮箱提供在线免费的一次性电子邮箱服务", link: "https://tempmail.cn/" },
    { name: "临时邮箱-10分钟邮箱", description: "临时邮箱确保你的电子邮件中不再出现垃圾邮件，也称为10分钟邮箱", link: "https://www.linshi-email.com/" },
    { name: "网站测速-网站速度诊断", description: "多线路、多地区速度测试您的网页速度", link: "https://www.itdog.cn/http/" },
    { name: "即时设计", description: "在同一个地方，构思、设计、协作，让你和团队更加高效", link: "https://js.design/" },
    { name: "Canva可画-在线设计协作平台", description: "心中所想，世界可见", link: "https://www.canva.cn/" },
    { name: "免费文本转语音 | TTS-Online", description: "支持2000+角色的多语言文本转语音与声音复刻服务", link: "https://acgn.ttson.cn/" },
    { name: "设计-Figma", description: "Figma 帮助设计和开发团队共同打造出色的产品", link: "https://www.figma.com/" },
    { name: "设计工具-MasterGo", description: "能让团队成员灵活高效地完成界面设计、原型搭建与产品迭代。", link: "https://mastergocn.com/" },
    { name: "Arya - 在线 Markdown 编辑器", description: "如标题所见，就是个在线 Markdown 编辑器", link: "https://markdown.lovejade.cn/" },
    { name: "AI抠图", description: "巨好用！而且免登录！", link: "https://www.pictech.cc/newpictech/rmbg" },
    { name: "圆角图片制作工具", description: "也是好用，我基本都用它", link: "https://uutool.cn/img-radius/" },
    { name: "多尺寸图片切割工具", description: "快速生成适配不同平台的图片尺寸", link: "https://nocode.host/aagzbm" },
    { name: "AI图片压缩工具", description: "使用AI技术智能压缩图片，减少文件大小同时保持良好视觉质量", link: "https://nocode.host/7d87b/1ic27swwpgfiu9d5t#/image-compressor" },
    { name: "在线视频压缩", description: "免费的在线视频压缩工具（本地压缩，设备有概率发热）", link: "https://www.redpandacompress.com/zh/" },
    { name: "在线视频转换器", description: "轻松将您的视频转换为 MP4、MOV、MKV 等", link: "https://www.freeconvert.com/zh/video-converter" },
    { name: "音频转换器", description: "在线转换音频文件的最佳网络应用程序", link: "https://www.freeconvert.com/zh/audio-converter" },
    { name: "MP3转换器", description: "最佳 MP3 转换器，可免费在线将任何文件转换为 MP3 格式", link: "https://www.freeconvert.com/zh/mp3-converter" },
    { name: "MP4到MP3转换器", description: "免费在线将 MP4 转换为 MP3", link: "https://www.freeconvert.com/zh/mp4-to-mp3" },
    { name: "视频转 MP3", description: "免费在线将视频转换为 MP3 格式", link: "https://www.freeconvert.com/zh/convert/video-to-mp3" },
    { name: "MP4转换器", description: "免费将您的文件与 MP4 进行相互转换", link: "https://www.freeconvert.com/zh/mp4-converter" },
    { name: "MOV到MP4转换器", description: "免费在线将 MOV 转换为 MP4", link: "https://www.freeconvert.com/zh/mov-to-mp4" },
    { name: "MP3到OGG转换器", description: "免费在线将 MP3 转换为 OGG。", link: "https://www.freeconvert.com/zh/mp3-to-ogg" },
    { name: "PDF在线查看", description: "可以使用网页框嵌入，格式为https://pdfjs.zhshh.cn/web/viewer?file=文件直链", link: "https://pdfjs.zhshh.cn" },
    { name: "Lemonflow", description: "在线文档编写、分享平台", link: "https://lemonflow.nocode.host/#/" },
    { name: "图片拼接PDF工具", description: "上传多张图片，一键生成PDF文件", link: "https://image-merge-pdf-tool.nocode.host/" }
  ],
  tutorial: [
    { name: "CoCo 手册", description: "CoCo 官方手册", link: "https://codemao-guide.yuque.com/bfiekm/sbo5kh" },
    { name: "青柠系列库", description: "青柠系控件和作品的文档", link: "https://qeeodocs.feishu.cn/wiki/space/7602553860552445127?ccm_open_type=lark_wiki_spaceLink&open_tab_from=wiki_home" },
    { name: "CoCo进阶手册", description: "非官方的拓展版手册，一本让你看得懂 学得会的优质手册ㄟ(≧◇≦)ㄏ", link: "https://www.yuque.com/xiaofeng-0fczj/rie0lc" },
    { name: "CoCo编辑器进阶教程", description: "内容独特，东西很多，也是一份很实用的文档～( ╯▽╰)", link: "https://www.yuque.com/ymgg/sth/coco_plus" },
    { name: "教程-CoCo搭建网页", description: "使用CoCo搭建网页教程", link: "https://www.yuque.com/seekyhor/horkj/asg9y4u689iqefkt" },
    { name: "教程-作品Undefined修复", description: "解决作品出现Undefined的问题", link: "https://codemao.yuque.com/kzbwh0/coco_guide/pbpwuf2y6nlvlnvh" },
    { name: "CoCo 源代码计划", description: "某个不自量力的家伙想要还原编程猫 CoCo 编辑器、CoCo Player 等的代码。", link: "https://gitee.com/glacier-studio/CoCo-Source-Code-Plan" },
    { name: "教程-添加旧版控件", description: "一个小教程", link: "https://codemao.yuque.com/kzbwh0/coco_guide/skvglb7vmbuleote" },
    { name: "Datacool Docs", description: "Datacool文档の回归(#^.^#)", link: "https://qeeodocs.feishu.cn/wiki/space/7575378877338553302?ccm_open_type=lark_wiki_spaceLink&open_tab_from=wiki_home" },
    { name: "CoCo 社群管理", description: "CoCo 社群管理公示", link: "https://codemao.yuque.com/kzbwh0/qsh1lg" },
    { name: "Qeeo-可能有点用小帮助", description: "可能有点用小帮助", link: "https://qeeodocs.feishu.cn/wiki/LNCcwOfodihGjnkI0g6cOntunzf" },
    { name: "MDN Web Docs", description: "Documenting CSS, HTML, and JavaScript, since 2005.", link: "https://developer.mozilla.org/zh-CN/" },
    { name: "CoCo Next - gitee", description: "基于 CoCo 源代码计划 二次开发的 CoCo，旨在通过直接修改编辑器代码的方式修复 CoCo 的缺陷、增强 CoCo 的功能。", link: "https://gitee.com/oldsquaw/CoCo-Next" },
    { name: "Authior 文档", description: "Authior面板 の 详细文档", link: "https://qeeodocs.feishu.cn/wiki/space/7570605807176531987?ccm_open_type=lark_wiki_spaceLink&open_tab_from=wiki_home" }
  ],
  ui: [
    { name: "Font Awesome", description: "Font Awesome 是目前全球最流行的矢量图标库与工具包", link: "https://fontawesome.com/" },
    { name: "在线颜文字大全", description: "好全的颜文字大全！", link: "https://www.lddgo.net/common/emoticons" },
    { name: "Emoji大全", description: "收录的Emoji特别全！", link: "https://emoji6.com/emojiallt/" },
    { name: "App 界面设计教程-来自B站", description: "学好 UI 设计，能一定程度上提升用户体验！", link: "https://www.bilibili.com/video/av245342425/" },
    { name: "MingCute Icon", description: "一个图标库，好用！", link: "https://www.mingcute.com/" },
    { name: "Mage Icons", description: "Mage Icons图标库，也是好东西", link: "https://mageicons.com/" },
    { name: "IconPark", description: "IconPark图标库，也是好用！", link: "https://iconpark.oceanengine.com/official" },
    { name: "Ionicons", description: "专为网页、iOS、安卓和桌面应用程序设计的优质图标。", link: "https://ionic.io/ionicons" },
    { name: "阿里巴巴矢量图标库", description: "国内功能很强大且图标内容很丰富的矢量图标库", link: "https://www.iconfont.cn/collections/index" },
    { name: "HarmonyOS图标库", description: "国内的HarmonyOS系统的图标库", link: "https://developer.huawei.com/consumer/cn/design/harmonyos-icon/" },
    { name: "The Thiings Collection", description: "庞大的Emoji表情库", link: "https://www.thiings.co/things" },
    { name: "Remix Icon", description: "又是一个图标库", link: "https://remixicon.com/" },
    { name: "lucide", description: "图标库一个", link: "https://lucide.dev/" },
    { name: "iconbox", description: "还是图标库一个", link: "https://arco.design/iconbox/libs" },
    { name: "iconify", description: "有分类的图标库一个", link: "https://icon-sets.iconify.design/" },
    { name: "MiSans", description: "小米的字体", link: "https://hyperos.mi.com/font/zh/" },
    { name: "阿里巴巴普惠体", description: "阿里巴巴普惠体开放商业授权给所有个人和商家", link: "https://www.alibabafonts.com/#/home" },
    { name: "思源宋体", description: "开源的泛 CJK 字体", link: "https://source.typekit.com/cn/" },
    { name: "平方造字", description: "平方-猫啃网", link: "https://www.maoken.com/?s=%E5%B9%B3%E6%96%B9" },
    { name: "云塔CDN-字体获取", description: "云塔静态资源加速服务 - 文件索引", link: "https://cdn.yuntower.com/font/" },
    { name: "iFonts字体", description: "以方·iFonts字体助手 ·", link: "https://ifonts.com/clientdown" },
    { name: "汉仪字库", description: "用心，绽放文字之美", link: "https://www.hanyi.com/home" },
    { name: "字由 | 免费字体大全", description: "5000+精选字体授权商用", link: "https://www.hellofont.cn/font-list" }
  ]
};
